/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    'Account.v1': {
      accountId?: string | null
      accountNumber?: string | null
      ownerCustomerId?: string | null
      name?: string | null
      accountType?: string | null
      available?: number | null
      balance?: number | null
      creditLimit?: number | null
    }
    'ErrorType.':
    | 'System'
    | 'Input'
    | 'State'
    | 'ServiceUnavailable'
    | 'CustomHttpStatus'
    | 'NotFound'
    'ListResult.Account.v1': {
      availableItems?: number
      items?: Array<components['schemas']['Account.v1']> | null
      errorType?: components['schemas']['ErrorType.']
      isError?: boolean
      errorCode?: number | null
      errorMessage?: string | null
      traceId?: string | null
    }
    'ItemResult.Account.v1': {
      item?: components['schemas']['Account.v1']
      errorType?: components['schemas']['ErrorType.']
      isError?: boolean
      errorCode?: number | null
      errorMessage?: string | null
      traceId?: string | null
    }
  }
}
