/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    'ReservationType.v1':
    | 'NotReservation'
    | 'VisaReservation'
    | 'PurchaseReservation'
    | 'AtmReservation'
    'SourceType.v1': 'AccountStatement' | 'Archive'
    'CardDetails.v1': {
      cardNumber?: string | null
      currencyAmount?: number
      currencyRate?: number
      merchantCategoryCode?: string | null
      merchantCategoryDescription?: string | null
      merchantCity?: string | null
      merchantName?: string | null
      originalCurrencyCode?: string | null
      purchaseDate?: string
      transactionId?: string | null
    }
    'TransactionDetail.v1': {
      formattedAccountNumber?: string | null
      transactionId?: number
      cid?: string | null
      amountDescription?: string | null
      receiverName?: string | null
      numericReference?: number
      payerName?: string | null
      registrationDate?: string | null
    }
    'Transaction.v1': {
      accountingDate?: string
      interestDate?: string | null
      otherAccountNumber?: string | null
      otherAccountNumberSpecified?: boolean
      amount?: number
      text?: string | null
      transactionType?: string | null
      transactionTypeCode?: number
      transactionTypeText?: string | null
      isReservation?: boolean
      reservationType?: components['schemas']['ReservationType.v1']
      source?: components['schemas']['SourceType.v1']
      cardDetailsSpecified?: boolean
      cardDetails?: components['schemas']['CardDetails.v1']
      transactionDetailSpecified?: boolean
      transactionDetail?: components['schemas']['TransactionDetail.v1']
    }
    'ErrorType.':
    | 'System'
    | 'Input'
    | 'State'
    | 'ServiceUnavailable'
    | 'CustomHttpStatus'
    | 'NotFound'
    'ListResult.Transaction.v1': {
      availableItems?: number
      items?: Array<components['schemas']['Transaction.v1']> | null
      errorType?: components['schemas']['ErrorType.']
      isError?: boolean
      errorCode?: number | null
      errorMessage?: string | null
      traceId?: string | null
    }
  }
}
